"""initial

Revision ID: 572d25ff2476
Revises: 5472ff1d2216
Create Date: 2026-04-12 10:30:14.185329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '572d25ff2476'
down_revision = '5472ff1d2216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('source_airport_id', sa.Integer(), nullable=False),
    sa.Column('destination_airport_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('base_price_economy', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_price_business', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_price_first', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('available_economy', sa.Integer(), nullable=False),
    sa.Column('available_business', sa.Integer(), nullable=False),
    sa.Column('available_first', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.ForeignKeyConstraint(['destination_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['source_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('flight_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'boarding', 'departed', 'in_air', 'landed', 'delayed', 'cancelled', name='flightstatusenum'), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('delay_reason', sa.String(length=255), nullable=True),
    sa.Column('gate_number', sa.String(length=20), nullable=True),
    sa.Column('terminal', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id')
    )
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.Enum('email_verify', 'password_reset', 'login_2fa', name='otppurposeenum'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('passport_number', sa.String(length=50), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passport_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('seat_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.Column('seat_class', sa.Enum('economy', 'business', 'first', name='seatclassenum'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_window', sa.Boolean(), nullable=True),
    sa.Column('is_aisle', sa.Boolean(), nullable=True),
    sa.Column('is_emergency_exit', sa.Boolean(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'seat_number', name='uix_flight_seat')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=7), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.Column('seat_class', sa.Enum('economy', 'business', 'first', name='bookingclassenum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='bookingstatusenum'), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('upi', 'credit_card', 'debit_card', 'net_banking', 'cash', name='paymentmethodenum'), nullable=False),
    sa.Column('payment_status', sa.Enum('initiated', 'success', 'failed', 'refunded', name='paymentstatusenum'), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refund_date', sa.DateTime(), nullable=True),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('booking_id'))

    op.drop_table('payment')
    op.drop_table('booking')
    with op.batch_alter_table('airport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('airport_code'))

    op.drop_table('airport')
    op.drop_table('flight')
    op.drop_table('flight_status')
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('passport_number'))

    op.drop_table('passenger')
    op.drop_table('pilot')
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('registration_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('economy_seats', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('business_seats', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('first_class_seats', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('seat_layout', sa.JSON(), nullable=False))
        batch_op.alter_column('model',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['registration_number'])
        batch_op.drop_column('aircraft_id')
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('aircraft_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('model',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('seat_layout')
        batch_op.drop_column('first_class_seats')
        batch_op.drop_column('business_seats')
        batch_op.drop_column('economy_seats')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('id')

    op.create_table('pilot',
    sa.Column('pilot_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pilot_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('gender', mysql.ENUM('Male', 'Female', 'Other'), nullable=True),
    sa.Column('date_of_joining', sa.DATE(), nullable=False),
    sa.Column('aircraft_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('flight_hours', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salary', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('pilot_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('passenger',
    sa.Column('passenger_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('gender', mysql.ENUM('Male', 'Female', 'Other'), nullable=True),
    sa.Column('passport_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('passenger_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('passport_number'), ['passport_number'], unique=True)

    op.create_table('flight_status',
    sa.Column('status_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flight_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('last_updated', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.flight_id'], name=op.f('flight_status_ibfk_1')),
    sa.PrimaryKeyConstraint('status_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('flight',
    sa.Column('flight_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flight_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('departure_time', mysql.DATETIME(), nullable=False),
    sa.Column('arrival_time', mysql.DATETIME(), nullable=False),
    sa.Column('source_airport', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('destination_airport', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aircraft_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pilot_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.aircraft_id'], name=op.f('flight_ibfk_3')),
    sa.ForeignKeyConstraint(['destination_airport'], ['airport.airport_id'], name=op.f('flight_ibfk_2')),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilot.pilot_id'], name=op.f('flight_ibfk_4')),
    sa.ForeignKeyConstraint(['source_airport'], ['airport.airport_id'], name=op.f('flight_ibfk_1')),
    sa.PrimaryKeyConstraint('flight_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('airport',
    sa.Column('airport_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('airport_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('airport_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('airport_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('airport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('airport_code'), ['airport_code'], unique=True)

    op.create_table('booking',
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_date', sa.DATE(), nullable=False),
    sa.Column('seat_number', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('status', mysql.ENUM('Confirmed', 'Cancelled', 'Pending'), nullable=True),
    sa.Column('passenger_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('flight_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.flight_id'], name=op.f('booking_ibfk_2')),
    sa.ForeignKeyConstraint(['passenger_id'], ['passenger.passenger_id'], name=op.f('booking_ibfk_1')),
    sa.PrimaryKeyConstraint('booking_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payment',
    sa.Column('payment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', mysql.ENUM('Card', 'UPI', 'Cash'), nullable=True),
    sa.Column('payment_status', mysql.ENUM('Success', 'Failed', 'Pending'), nullable=True),
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], name=op.f('payment_ibfk_1')),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('booking_id'), ['booking_id'], unique=True)

    op.drop_table('payments')
    op.drop_table('bookings')
    op.drop_table('seat_maps')
    op.drop_table('passengers')
    op.drop_table('otps')
    op.drop_table('flight_statuses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('flights')
    op.drop_table('roles')
    op.drop_table('airports')
    # ### end Alembic commands ###
